/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_ianbeltrand_22141085;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author kevin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() throws IOException {
        initComponents();
        
        admi.CargarArchivo();
        ActualizarCancionesTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTotal = new javax.swing.JLabel();
        NotaBarra = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        TreeCanciones = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        CancionTexto = new javax.swing.JTextArea();
        GrabarCancionButton = new javax.swing.JButton();
        GuardarCancionButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        PausarCancionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTotal.setText("Texto Provisional");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Canciones");
        TreeCanciones.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        TreeCanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TreeCancionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TreeCanciones);

        CancionTexto.setEditable(false);
        CancionTexto.setColumns(20);
        CancionTexto.setRows(5);
        jScrollPane2.setViewportView(CancionTexto);

        GrabarCancionButton.setText("Grabar Cancion");
        GrabarCancionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GrabarCancionButtonMouseClicked(evt);
            }
        });

        GuardarCancionButton.setText("Guardar Cancion");
        GuardarCancionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarCancionButtonMouseClicked(evt);
            }
        });

        jButton3.setText("Reproducir Cancion");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        PausarCancionButton.setText("Pausar Cancion");
        PausarCancionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PausarCancionButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NotaBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelTotal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(GrabarCancionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GuardarCancionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PausarCancionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 233, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelTotal)
                .addGap(18, 18, 18)
                .addComponent(NotaBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GrabarCancionButton)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GuardarCancionButton)
                            .addComponent(PausarCancionButton))
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GrabarCancionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrabarCancionButtonMouseClicked
        // TODO add your handling code here:
        LabelTotal.setText("Grabando...");
        CancionTexto.setEditable(true);
        CancionTexto.setText("");
        GrabarSong = new HiloGrabar(NotaBarra, CancionTexto);
        Thread proceso = new Thread(GrabarSong);
        proceso.start();
    }//GEN-LAST:event_GrabarCancionButtonMouseClicked

    public void ActualizarCancionesTree(){
        DefaultTreeModel model = (DefaultTreeModel)TreeCanciones.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)model.getRoot();
        root.removeAllChildren();
        
        for (Canciones cancion : admi.getCanciones()) {
            int centinela = 0;
            
            for (int i = 0; i < root.getChildCount(); i++) {
                if(root.getChildAt(i).toString().equals(cancion.getCategoria())){
                    DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(cancion);
                    
                    ((DefaultMutableTreeNode)root.getChildAt(i)).add(newNode);
                    centinela = 1;
                }
            }
            
            if(centinela == 0){
                DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(cancion.getCategoria());
                DefaultMutableTreeNode nodeSong = new DefaultMutableTreeNode(cancion);
                
                newNode.add(nodeSong);
                root.add(newNode);
            }
        }
        
        model.reload();
    }
    
    private void GuardarCancionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarCancionButtonMouseClicked
        // TODO add your handling code here:
        GrabarSong.setGrabando(false);
        CancionTexto.setEditable(false);
        LabelTotal.setText("|- - -|");
        
        String name = JOptionPane.showInputDialog(this, "Nombre de la cancion: ");
        String category  = JOptionPane.showInputDialog(this, "Categoria de la cancion: ");
        String letter = CancionTexto.getText();
        
        Canciones cancion = new Canciones(name, category, letter);
        admi.getCanciones().add(cancion);
        
        try {
            admi.GuardarArchivo();
        } catch (IOException ex) {
            
        }
        
        ActualizarCancionesTree();
        
        JOptionPane.showMessageDialog(this, "SE HA CREADO EXITOSAMENTE LA CANCION!!!");
    }//GEN-LAST:event_GuardarCancionButtonMouseClicked

    private void TreeCancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TreeCancionesMouseClicked
        // TODO add your handling code here:
        int Row = TreeCanciones.getClosestRowForLocation(evt.getX(), evt.getY());
        TreeCanciones.setSelectionRow(Row);
        Object Posicion = TreeCanciones.getSelectionPath().getLastPathComponent();
        SelectedNode = (DefaultMutableTreeNode)Posicion;
        
        if(SelectedNode.getUserObject() instanceof Canciones){
            cancionActual = (Canciones)SelectedNode.getUserObject();
        }
    }//GEN-LAST:event_TreeCancionesMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        LabelTotal.setText("Reproduciendo: " + cancionActual.getNombre());
        CancionTexto.setText("");
        ReproducirSong = new HiloReproducir(NotaBarra, CancionTexto, cancionActual, tiempo);
        Thread proceso = new Thread(ReproducirSong);
        proceso.start();
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void PausarCancionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PausarCancionButtonMouseClicked
        // TODO add your handling code here:
        if(PausaV == 0){
            PausaV = 1;
            PausarCancionButton.setText("Reanudar Cancion");
            ReproducirSong.setPausar(true);
        }else{
            PausaV = 0;
            PausarCancionButton.setText("Pausar Cancion");
            ReproducirSong.setPausar(false);
        }
    }//GEN-LAST:event_PausarCancionButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Principal().setVisible(true);
                } catch (IOException ex) {
                    
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CancionTexto;
    private javax.swing.JButton GrabarCancionButton;
    private javax.swing.JButton GuardarCancionButton;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JProgressBar NotaBarra;
    private javax.swing.JButton PausarCancionButton;
    private javax.swing.JTree TreeCanciones;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
    HiloGrabar GrabarSong;
    HiloReproducir ReproducirSong;
    Admi admi = new Admi();
    Canciones cancionActual;
    DefaultMutableTreeNode SelectedNode;
    int PausaV = 0;
    boolean tiempo = true;
}
